-- MySQL Script generated by MySQL Workbench
-- dom 10 sep 2023 22:54:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appcitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appcitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appcitas` DEFAULT CHARACTER SET utf8 ;
USE `appcitas` ;

-- -----------------------------------------------------
-- Table `appcitas`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcitas`.`pacientes` (
  `idpacientes` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `pacientescol` ENUM('M', 'F', 'O') NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idpacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appcitas`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcitas`.`medicos` (
  `idmedicos` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmedicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appcitas`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcitas`.`citas` (
  `idcitas` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `motivo` VARCHAR(200) NOT NULL,
  `citascol` VARCHAR(45) NULL,
  `medicos_idmedicos` INT NOT NULL,
  `pacientes_idpacientes` INT NOT NULL,
  PRIMARY KEY (`idcitas`),
  INDEX `fk_citas_medicos1_idx` (`medicos_idmedicos` ASC) VISIBLE,
  INDEX `fk_citas_pacientes1_idx` (`pacientes_idpacientes` ASC) VISIBLE,
  CONSTRAINT `fk_citas_medicos1`
    FOREIGN KEY (`medicos_idmedicos`)
    REFERENCES `appcitas`.`medicos` (`idmedicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citas_pacientes1`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `appcitas`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appcitas`.`historial_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcitas`.`historial_medico` (
  `idhistorial_medico` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  `diagnostico` VARCHAR(200) NOT NULL,
  `tratamiento` VARCHAR(200) NOT NULL,
  `medicamentos` VARCHAR(200) NOT NULL,
  `pacientes_idpacientes` INT NOT NULL,
  PRIMARY KEY (`idhistorial_medico`),
  INDEX `fk_historial_medico_pacientes1_idx` (`pacientes_idpacientes` ASC) VISIBLE,
  CONSTRAINT `fk_historial_medico_pacientes1`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `appcitas`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
