# Generated by Django 4.2.5 on 2023-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0002_user_is_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="passord",
            new_name="password",
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
