# Generated by Django 4.2.5 on 2023-10-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_rename_passord_user_password_alter_user_bio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birth_date",
            new_name="birthdate",
        ),
    ]
